services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - hbx-network
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
    ports:
      - '3002:3002'
    networks:
      - hbx-network

networks:
  hbx-network:
    driver: bridge